service: secret-awsome-stats

provider:
  name: aws
  runtime: nodejs8.10

functions:
  downloads:
    handler: handler.downloads
    events:
      - http:
          path: downloads
          method: get
